#!/bin/bash

# Run the MeTTa porting script and capture output, wrapping each entry
# in !(compileadd kb ...) so the output file can be directly imported into tests.
metta port_logic.metta | python3 -c "
import sys, re
output = sys.stdin.read()
# Replace symbolic placeholders with real MeTTa variables
output = output.replace('Sphi', '\$phi').replace('Spsi', '\$psi').replace('Schi', '\$chi').replace('Stheta', '\$theta').replace('Stau', '\$tau')
atoms = re.findall(r'\(: .*?\(STV 1.0 1.0\)\)', output)
with open('pettachainer_output.metta', 'w') as f:
    f.write(';; Auto-generated by run_porting.sh — do not edit manually.\n')
    f.write(';; Import this file into a PeTTaChainer test to load all ported axioms/theorems.\n\n')
    for atom in atoms:
        f.write(f'!(compileadd kb {atom})\n')
"

echo "Porting complete. Results saved to pettachainer_output.metta"
